name: MAUI Unit Tests
 
on:
  push:
    branches:
      - main
      - infra/runner-toevoegen
  pull_request:
    branches:
      - main
 
jobs:
  test:
    runs-on: macOS-latest  # Of windows-latest/macOS-latest/ubuntu-latest als specifiek platform nodig is (ubuntu-latest is de standaard)
    steps:
      - name: Haal de repository op
        uses: actions/checkout@v4
 
      - name: Installeer .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Gebruik de juiste versie voor MAUI
          
      - name: Herstel afhankelijkheden
        run: dotnet restore
 
      - name: Build core projects
        run: |
          dotnet build --configuration Release ./Grocery.Core/Grocery.Core.csproj
          dotnet build --configuration Release ./Grocery.Core.Data/Grocery.Core.Data.csproj